[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/bylaws',
    'pallets/coin-voting',
    'pallets/compat',
    'pallets/organizations',
    'pallets/tokens',
    'primitives',
    'runtime',
    'support',
    'voting',
]