[package]
edition = '2018'
license = 'Apache 2.0'
name = 'governance-os-runtime'
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
wasm-builder-runner = { package = 'substrate-wasm-builder-runner', version = '1.0.5' }

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies]
frame-executive = { version = "2.0.0", default-features = false }
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
governance-os-pallet-tokens = { version = "2.0.0", default-features = false, path = '../pallets/tokens' }
governance-os-primitives = { version = "2.0.0", default-features = false, path = '../primitives' }
pallet-indices = { version = "2.0.0", default-features = false }
serde = { version = "1.0.116", optional = true }
sp-api = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
sp-version = { version = "2.0.0", default-features = false }
static_assertions = "1.1.0"

[features]
default = ['std']
std = [
    'codec/std',
    'frame-executive/std',
    'frame-support/std',
    'frame-system/std',
    'governance-os-pallet-tokens/std',
    'governance-os-primitives/std',
    'pallet-indices/std',
    'serde',
    'sp-api/std',
    'sp-runtime/std',
    'sp-std/std',
    'sp-version/std',
]